CREATE DATABASE IF NOT EXISTS merviq_technologies CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE merviq_technologies;
CREATE TABLE IF NOT EXISTS contact_messages (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(190) NOT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  company VARCHAR(150) DEFAULT NULL,
  inquiry TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
